### ISSUE TITLE
Add function(s) to disable hyper indices and add further utility functions for working with hyper indices

### ISSUE THREAD

**Issue by nmoran** [JuliaQX/QXTns.jl#9]
In the current implementation hyper indices are automatically detected. This is not always desirable and we may want to disable this detection. This can be done by either clearing the arrays of identified indices or not trying to find them in the first place.

**Comment by nmoran** [comment]
@JuliaRegistrator register

**Comment by nmoran** [comment]
@JuliaRegistrator register

**Comment by brenjohn** [comment]
@JuliaRegistrator register
